### ISSUE TITLE
Project setup: 2-people team

### ISSUE THREAD

**Issue by Zibilyonik** [elasfarc/game-rating#21]
Project link: https://github.com/elasfarc/game-rating

Good day, we have a team of 2 to work on this project. 
Student A: Onur Onat Surmeli
Student B: Mohammed Al-Asfar

Thank you for your time.

**Comment by Dipeshtwis** [comment]
Hi @Zibilyonik and @elasfarc, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] For a team with 2 people - All cards with `Student C` suffix on the template should be removed from the template. **Number of cards in Backlog should be equal to 15.** Currently, you have **20 cards** in backlog.
- [x] Also decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
- [x] The issue should use a circle with user's avatar on each card. See the example below:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">

### Your's issue card look like:

![Screenshot from 2021-08-02 19-03-35](https://user-images.githubusercontent.com/22434660/127870350-40886245-c570-4135-8c7f-a17daf588893.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It's better if you mention the two name and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Zibilyonik** [comment]
> Hi @Zibilyonik and @elasfarc,
> 
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [x]  For a team with 2 people - All cards with `Student C` suffix on the template should be removed from the template. **Number of cards in Backlog should be equal to 15.** Currently, you have **20 cards** in backlog.
> * [x]  Also decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
> * [x]  The issue should use a circle with user's avatar on each card. See the example below:
> 
> <img alt="assigned_card" width="372" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">
> 
> ### Your's issue card look like:
> ![Screenshot from 2021-08-02 19-03-35](https://user-images.githubusercontent.com/22434660/127870350-40886245-c570-4135-8c7f-a17daf588893.png)
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> * It's better if you mention the two name and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.
> 
> Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> **_Dipesh Kumar_**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

All requested changes have been made, thank you.

**Comment by Dipeshtwis** [comment]
Hi @Zibilyonik and @elasfarc, 

Great work on making the changes requested in a previous review 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [x] All cards with group task in the title should be assigned to someone (it does not matter to whom as you have freedom with that).


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new issue link for re-reviews. You should use the same issue link submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mricanho** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @Zibilyonik @elasfarc  🔥 

You worked hard in all the instructions that the previous Code Reviewer gives you👍🏽 

![yougotit](https://user-images.githubusercontent.com/60631456/127875219-af3d1ef3-585d-4f8b-8d63-b0d56f381862.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
